" Auto-command

set modeline

filetype plugin indent on

" Display

set ruler
set number
set relativenumber

" Tab

set expandtab
set softtabstop=2
set shiftwidth=2

" Spell

set spell

" Mapping

nnoremap <C-j> /<++><CR>"_cf>
inoremap <C-j> <ESC>/<++><CR>"_cf>

" Trailing Blank Check

autocmd BufWrite * %s/ \+$//e
