" Auto-command

set modeline

filetype plugin indent on

" Display

set ruler
set number
set relativenumber

" Spell

set spell

" Mapping

nnoremap <C-j> /<++><CR>"_cf>
inoremap <C-j> <ESC>/<++><CR>"_cf>
