" VI compatible

set nocompatible

" Auto-command

set modeline
set autoread

filetype plugin indent on

" Display

set laststatus=2
set report=0

set ruler
set showcmd
set showmode

set number
set relativenumber

set showbreak=++++

" Tab

set expandtab
set softtabstop=2
set shiftwidth=2

" Spell

set spell

" Mapping

nnoremap <C-j> /<++><CR>"_cf>
inoremap <C-j> <ESC>/<++><CR>"_cf>

inoremap <buffer> () ()<++><ESC>F)i
inoremap <buffer> [] []<++><ESC>F]i
inoremap <buffer> {} {}<++><ESC>F}i

" Completion

set wildmode=longest:list

" Misc

set autoindent

set whichwrap=

" Trailing Blank Check

autocmd BufWrite * %s/ \+$//e
